name: CI

on: [push]

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable yarn

      - name: Cache
        uses: actions/cache@v4
        with:
          save-always: true
          path: ~/.cache/yarn
          key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Install deps
        run: yarn install

      - name: Building @fluer/mordred
        working-directory: pkgs/mordred
        run: |
          yarn eslint
          yarn prepublishOnly
